# Site settings
title: Ashish Singh
description: 'Ashish Portfolio'
url: 'https://ashishjublsdet.github.io/'
baseurl: ''
profilepic: '/images/ashish.jpg'
bkimage: '/images/bk1.jpg'
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Ashish Singh'
  email: ashishsdet88@gmail.com
  github_username:  ashishjublsdet
  linkedin_username:  ashish-singh-7106558b

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

exclude: ['README.md', 'screenshot-overview.png']
